### ISSUE TITLE
Rate limiting details

### ISSUE THREAD

**Issue by hontarenkoYana** [jxmorris12/language_tool_python#8]
Hello! 
I found your library very cool and easy to use.
But I have one question: in documentation you wrote that using Public HTTP Proofreading API have limitation. 
However, when I try to check this and run following code I didn't find any limitations and errors.
```
import language_tool_python
tool = language_tool_python.LanguageToolPublicAPI('es')
for _ in range(10000):
    matches = tool.check(text)
    print(matches)
```
Can you help me with this? I just want to understand why this happened.

**Comment by jxmorris12** [comment]
Hi @hontarenkoYana  -- great question. This was working so well because the LanguageTool client was sneakily connecting to a local instance, not the remote instance, so there was no rate limiting.

If you update (`pip install language_tool_python --upgrade`) and try the new version, your code should actually contact the remote server (https://api.languagetool.org/v2/). Don't send too many requests, or they'll ban you :)

**Comment by hontarenkoYana** [comment]
@jxmorris12, okay, I understand this. 
Am I right, that local instance is free and i have no limitations with it?

**Comment by jxmorris12** [comment]
Yes! There are no limitations on the local instance @hontarenkoYana.

**Comment by hontarenkoYana** [comment]
@jxmorris12, thank you for answering!
